### ISSUE TITLE
Introduce Error Codes for different type of Exceptions

### ISSUE THREAD

**Issue by subham37853** [prolevel1/UnitTestSpringBootApplication#1]
### Introduction to Error Codes for Exceptions in the Application

When trying to deal with exception handling, in the response we should get something like below
```
{
   “Error” : {
                     “ErrorCode : 10001”,
                     ”errorDescription : “OBJECT_NOT_FOUND”,
                     ”debugCode” : 1890
                   }
}
```
Here the `Error` identifies as a class with the following structure
```
class Error {
    private int errorCode;
    private int errorDescription; 
    private int debugCode;
}
```

**Comment by Shubham-Xperi** [comment]
@prolevel1 please resolve (mark this as done) this issue

**Comment by prolevel1** [comment]
Resolved this issue.
